name: CDCI-BD07

on:
  push:
    paths-ignore:
      - "README.md"
    branches: [ "master" ]
  pull_request:
    paths-ignore:
      - "README.md"
    branches: [ "master" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Notify MS Teams ERROR in linter
        if: ${{ failure() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}        
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Linting error!'
          color: 'failure'

      - name: Notify MS Teams SUCCESS in linter
        if: ${{ success() }}
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}        
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          deploy-card: true
          title: 'Linting successful!'
          color: 'success'     
      
      
  build:
    runs-on: ubuntu-latest
    needs: run-lint
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
    - name: Notify MS Teams ERROR for build
      if: ${{ failure() }}
      uses: mikesprague/teams-incoming-webhook-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}        
        webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        deploy-card: true
        title: 'Build error!'
        color: 'failure'
        
    - name: Notify MS Teams SUCCESS for build
      if: ${{ success() }}
      uses: mikesprague/teams-incoming-webhook-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}        
        webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        deploy-card: true
        title: 'Build was succesful!'
        color: 'success'
        
        

  
